server:
  port: 4002

#eureka:
#  instance:
#    hostname: localhost
#    port: 4001
#  client:
#    registerWithEureka: true
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#  server:
#    wait-time-in-ms-when-sync-empty: 3000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://ecommerce-eureka-server.herokuapp.com/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 'postgres'
    url: jdbc:postgresql://localhost:5433/ecommerce_category
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
  jackson:
    parser:
      allow-numeric-leading-zeros: true
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
